### ISSUE TITLE
Flatrun Roadmap

### ISSUE THREAD

**Issue by ryanabx** [ryanabx/flatrun#5]
## Quality of life
- [x] `--gui` mode for when running Flatrun via the .desktop file. Will show progress bars and info for the progress on the app running. (Add wayland/x11 socket in permissions)
- [x] Default to asking the file using the file chooser portal

## Security/Sandboxing
- [x] Use xdg file chooser portal when specifying the file as a command line arg AND when not specifying a file on initial run
- [x] Remove filesystem=host permission

## Config
- [ ] Add simple config of what installation to use when downloading new runtimes (should pop up a window asking user pref if the config doesn't exist in `--gui` mode, or ask the option in the CLI.

## Flathub
- [x] Begin review process by submitting a PR in https://github.com/flathub/flathub
- [ ] Get review accepted and publish to flathub

## Documentation
- [x] Create https://github.io/ryanabx/flatrun
- [ ] Document commands that can be run
